
name: CI
on: [push]

jobs:
  build-linux:
    name: Build Linux 64-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
          lfs: true
      - run: sudo apt-get install -y nasm
      - run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
      - run: cmake --build build --config RelWithDebInfo
      - run: mkdir build-debug && strip -g -o build-debug/libSpicyTemple.Native.so build/libSpicyTemple.Native.so
      - uses: actions/upload-artifact@master
        with:
          name: native_lib_linux
          path: 'build/libSpicyTemple.Native.so'
      - uses: actions/upload-artifact@master
        with:
          name: native_lib_linux_stripped
          path: 'build-debug/libSpicyTemple.Native.so'

  build-windows:
    name: Build Windows 64-bit
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
        lfs: true
    - run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
      shell: bash
    - run: cmake --build build --config RelWithDebInfo
      shell: bash
    - uses: actions/upload-artifact@master
      with:
          name: native_lib_windows
          path: 'build/RelWithDebInfo/SpicyTemple.Native.dll'
    - uses: actions/upload-artifact@master
      with:
          name: native_lib_windows_pdb
          path: 'build/RelWithDebInfo/SpicyTemple.Native.pdb'

  build-macosx:
    name: Build MacOSX 64-bit
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
          lfs: true
      - script: brew install ninja nasm          
      - run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja ..
      - run: cmake --build build --config RelWithDebInfo
      - run: mkdir build-debug && strip -g -o build-debug/libSpicyTemple.Native.dylib build/libSpicyTemple.Native.dylib
      - uses: actions/upload-artifact@master
        with:
          name: native_lib_macos
          path: 'build/libSpicyTemple.Native.dylib'
      - uses: actions/upload-artifact@master
        with:
          name: native_lib_macos_stripped
          path: 'build-debug/libSpicyTemple.Native.dylib'
